### PR TITLE
Initial commit of updating pyo3 methods

### PR DESCRIPTION
**Pull request by timsaucer**
## Which issue does this PR close?

Closes #.

### CODE REVIEW

**Comment by timsaucer** [comment]
@alamb work in progress, but it shouldn't be too hard to wrap up any remaining issues. I want to test it with `datafusion-python` before I mark it ready

**Review by alamb — APPROVED** [review]
Thanks @timsaucer  ❤️

**Comment by timsaucer** [comment]
Ok, I pulled in these changes to datafusion-python and see no regression

**Comment by timsaucer** [comment]
@alamb since this targets your fork I can't merge, but I think this is ready for you.

**Comment by alamb** [comment]
Thanks @timsaucer  -- I plan to work on the arrow-rs release this weekend too so hopefully we'll be close with that

**Pull request merged**
